# Generated by Django 4.2.19 on 2025-03-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='ingredients'),
        ),
    ]
